// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq2NqUGB4WqnOtWg6FWwI5FSqh5TegMM4',
    appId: '1:510512275239:web:c8b5def9a27a7cdbda1302',
    messagingSenderId: '510512275239',
    projectId: 'poster-sale',
    authDomain: 'poster-sale.firebaseapp.com',
    storageBucket: 'poster-sale.firebasestorage.app',
    measurementId: 'G-6DJ2W8R4RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDln5BV0WUnw1sJ_J7ig4eEBRbiKLD_XE4',
    appId: '1:510512275239:android:50191945436e3c55da1302',
    messagingSenderId: '510512275239',
    projectId: 'poster-sale',
    storageBucket: 'poster-sale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAss0-hAJMefiCdysIMH0QA8JKibJ2nTlo',
    appId: '1:510512275239:ios:c6d12fbb1f8f0d17da1302',
    messagingSenderId: '510512275239',
    projectId: 'poster-sale',
    storageBucket: 'poster-sale.firebasestorage.app',
    iosBundleId: 'com.isi.posterSale',
  );
}
